# Generated by Django 3.2.2 on 2021-05-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(verbose_name='ID в Telegram')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('karma', models.IntegerField(default=50, verbose_name='Опыт')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень игрока')),
                ('total', models.IntegerField(default=0, verbose_name='Опыт')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-total', 'name'],
            },
        ),
    ]
