# Generated by Django 3.2.2 on 2021-05-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ending',
            field=models.CharField(default='not_started', max_length=255, verbose_name='Концовка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото Профиля'),
        ),
    ]
