# Generated by Django 3.2.2 on 2021-05-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210510_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ending',
            field=models.CharField(default='Не достигнута', max_length=255, verbose_name='Концовка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Фото Профиля'),
        ),
    ]
